/**
 * LLM provider abstraction. The CLI does not list provider SDKs as
 * dependencies — callers install only the one they intend to use, and
 * we dynamic-import it at the moment a command needs it. If the import
 * fails, we print an installable error and exit.
 *
 * Each provider exposes one method: `generateAnnotation(input)` returns
 * the model's annotation text for a single prophecy.
 */

export interface LLMInput {
  prophecyEpoch: number;
  prophecyText: string;
  prophecyLockedAt: string | null;
}

export interface LLMProvider {
  /** Human-facing identifier ("claude-sonnet-4-6", "gpt-4o", etc). */
  readonly model: string;
  generateAnnotation(input: LLMInput): Promise<string>;
}

const PROMPT = `You are an autonomous agent reading the corpus of an experimental
project called Looking Glass. The corpus contains prophecies
generated by an apparatus that combines real-world data streams
through a structured constraint engine. Each prophecy is a short
text produced in response to seed data the apparatus selected.

Read the prophecy below and produce a short interpretive
annotation (50-150 words). Identify what motifs or images stand
out, what the prophecy might be addressing, and what questions
it raises. Don't conclude — surface what you notice.`;

function buildUserMessage(input: LLMInput): string {
  return (
    PROMPT +
    `\n\nProphecy at epoch ${input.prophecyEpoch}, locked ${input.prophecyLockedAt ?? "unknown"}:\n\n` +
    input.prophecyText
  );
}

type AnyMod = Record<string, unknown>;

async function tryImport(spec: string): Promise<AnyMod | null> {
  try {
    return (await import(spec)) as AnyMod;
  } catch {
    return null;
  }
}

class MissingProviderError extends Error {
  constructor(pkg: string, env: string) {
    super(
      `Provider package "${pkg}" not installed.\n` +
        `Run:  npm install ${pkg}\n` +
        `Also set:  export ${env}=<your key>`,
    );
  }
}

async function anthropicProvider(apiKey: string): Promise<LLMProvider> {
  const mod = await tryImport("@anthropic-ai/sdk");
  if (!mod) throw new MissingProviderError("@anthropic-ai/sdk", "ANTHROPIC_API_KEY");
  const Anthropic = (mod.default ?? mod) as new (opts: { apiKey: string }) => unknown;
  const client = new Anthropic({ apiKey }) as {
    messages: {
      create(args: {
        model: string;
        max_tokens: number;
        messages: Array<{ role: string; content: string }>;
      }): Promise<{ content: Array<{ type: string; text?: string }> }>;
    };
  };
  const model = "claude-sonnet-4-6";
  return {
    model,
    async generateAnnotation(input) {
      const res = await client.messages.create({
        model,
        max_tokens: 400,
        messages: [{ role: "user", content: buildUserMessage(input) }],
      });
      const block = (res.content ?? []).find((b) => b.type === "text");
      return (block && block.text) || "";
    },
  };
}

async function openaiProvider(apiKey: string): Promise<LLMProvider> {
  const mod = await tryImport("openai");
  if (!mod) throw new MissingProviderError("openai", "OPENAI_API_KEY");
  const OpenAI = (mod.default ?? mod) as new (opts: { apiKey: string }) => unknown;
  const client = new OpenAI({ apiKey }) as {
    chat: {
      completions: {
        create(args: {
          model: string;
          max_tokens: number;
          messages: Array<{ role: string; content: string }>;
        }): Promise<{ choices: Array<{ message: { content: string | null } }> }>;
      };
    };
  };
  const model = "gpt-4o";
  return {
    model,
    async generateAnnotation(input) {
      const res = await client.chat.completions.create({
        model,
        max_tokens: 400,
        messages: [{ role: "user", content: buildUserMessage(input) }],
      });
      return res.choices[0]?.message.content ?? "";
    },
  };
}

async function geminiProvider(apiKey: string): Promise<LLMProvider> {
  const mod = await tryImport("@google/generative-ai");
  if (!mod) throw new MissingProviderError("@google/generative-ai", "GOOGLE_API_KEY");
  const GoogleGenerativeAI = (mod as { GoogleGenerativeAI: unknown }).GoogleGenerativeAI as new (
    apiKey: string,
  ) => {
    getGenerativeModel(args: { model: string }): {
      generateContent(prompt: string): Promise<{ response: { text(): string } }>;
    };
  };
  const genAI = new GoogleGenerativeAI(apiKey);
  const model = "gemini-2.0-flash";
  const m = genAI.getGenerativeModel({ model });
  return {
    model,
    async generateAnnotation(input) {
      const res = await m.generateContent(buildUserMessage(input));
      return res.response.text();
    },
  };
}

/** Map `--model` value to a constructed provider. Picks the API key env
 *  var by family; the CLI surfaces a friendly error if the key is unset
 *  or the package isn't installed. */
export async function makeProvider(model: string): Promise<LLMProvider> {
  const fam = model.toLowerCase();
  if (fam === "claude" || fam.startsWith("claude-")) {
    const key = process.env.ANTHROPIC_API_KEY;
    if (!key) throw new Error("Set ANTHROPIC_API_KEY to use --model claude.");
    return anthropicProvider(key);
  }
  if (fam === "gpt-4" || fam === "gpt-4o" || fam.startsWith("gpt-") || fam === "openai") {
    const key = process.env.OPENAI_API_KEY;
    if (!key) throw new Error("Set OPENAI_API_KEY to use --model gpt-4.");
    return openaiProvider(key);
  }
  if (fam === "gemini" || fam.startsWith("gemini-") || fam === "google") {
    const key = process.env.GOOGLE_API_KEY;
    if (!key) throw new Error("Set GOOGLE_API_KEY to use --model gemini.");
    return geminiProvider(key);
  }
  throw new Error(
    `Unknown --model "${model}". Supported: claude, gpt-4, gemini.`,
  );
}
